In [71]:
import numpy as np
from sklearn.decomposition import PCA

In [72]:
# generate random data
np.random.seed(0)
X_data = np.round(np.random.randn(15, 5), 2)
X_data

array([[ 1.76,  0.4 ,  0.98,  2.24,  1.87],
       [-0.98,  0.95, -0.15, -0.1 ,  0.41],
       [ 0.14,  1.45,  0.76,  0.12,  0.44],
       [ 0.33,  1.49, -0.21,  0.31, -0.85],
       [-2.55,  0.65,  0.86, -0.74,  2.27],
       [-1.45,  0.05, -0.19,  1.53,  1.47],
       [ 0.15,  0.38, -0.89, -1.98, -0.35],
       [ 0.16,  1.23,  1.2 , -0.39, -0.3 ],
       [-1.05, -1.42, -1.71,  1.95, -0.51],
       [-0.44, -1.25,  0.78, -1.61, -0.21],
       [-0.9 ,  0.39, -0.51, -1.18, -0.03],
       [ 0.43,  0.07,  0.3 , -0.63, -0.36],
       [-0.67, -0.36, -0.81, -1.73,  0.18],
       [-0.4 , -1.63,  0.46, -0.91,  0.05],
       [ 0.73,  0.13,  1.14, -1.23,  0.4 ]])

In [73]:
# perform PCA
pca = PCA(n_components=2)
pca.fit(X_data)
X_pca = pca.transform(X_data)
# transformed data
X_pca

array([[ 3.21928229, -1.27531524],
       [ 0.23322856,  0.21326981],
       [ 0.75013107, -1.18465437],
       [ 0.45722842, -0.85572944],
       [ 0.07424026,  0.824976  ],
       [ 1.85440262,  1.41411254],
       [-1.73816085, -0.30136739],
       [ 0.03662805, -1.44631654],
       [ 1.27228649,  2.69300441],
       [-1.58758653,  0.18699988],
       [-1.01256071,  0.3777244 ],
       [-0.4323018 , -0.62056989],
       [-1.56608462,  0.65763372],
       [-0.94471058,  0.68504597],
       [-0.61602267, -1.36881385]])

In [74]:
# explained variance ratio
pca.explained_variance_ratio_, sum(pca.explained_variance_ratio_)

(array([0.358819  , 0.25853032]), 0.6173493128005983)

In [75]:
# basis vectors
pca.components_

array([[ 0.13562921,  0.17132699,  0.07484863,  0.91498716,  0.33082921],
       [-0.65225968, -0.52292827, -0.50075286,  0.22047095,  0.04174291]])

In [76]:
# transform back to original space
X_ipca = pca.inverse_transform(X_pca)
X_ipca - X_data

array([[-0.80753457,  0.987115  ,  0.03357662,  0.134432  , -0.55953609],
       [ 0.55652531, -0.8528998 ,  0.19466137,  0.07042093, -0.02527201],
       [ 0.41844197, -0.53332638,  0.02336535,  0.01517843,  0.05738102],
       [-0.02582866, -0.79551265,  0.80673188, -0.37030535,  1.26421055],
       [ 1.70597056, -0.90001724, -1.13355231,  0.69981212, -1.91233559],
       [ 0.46314257, -0.30310353, -0.24532141,  0.18852531, -0.49881362],
       [-0.50517559, -0.35153367,  1.04481162,  0.03316239,  0.06105234],
       [ 0.4723418 , -0.29873816, -0.3390113 , -0.18535658,  0.55041084],
       [-0.84997898,  0.39839555,  0.59069924, -0.48214497,  1.34199003],
       [-0.21329559,  1.04888272, -0.8584694 , -0.09139325, -0.00874741],
       [ 0.2002928 , -0.59233507,  0.37906465,  0.04679721,  0.00944933],
       [-0.39986003,  0.34911524,  0.11239495, -0.19236823,  0.48974421],
       [-0.28735478, -0.08354116,  0.49746875,  0.15204181, -0.37198832],
       [-0.49095822,  1.27858235, -0.7

In [77]:
np.sum((X_ipca - X_data)**2)

28.50819047763819